// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	domain "school21/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// GameRepository is an autogenerated mock type for the GameRepository type
type GameRepository struct {
	mock.Mock
}

type GameRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *GameRepository) EXPECT() *GameRepository_Expecter {
	return &GameRepository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: id
func (_m *GameRepository) Get(id uuid.UUID) (domain.Game, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(uuid.UUID) (domain.Game, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(uuid.UUID) domain.Game); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Game)
	}

	if rf, ok := ret.Get(1).(func(uuid.UUID) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type GameRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id uuid.UUID
func (_e *GameRepository_Expecter) Get(id interface{}) *GameRepository_Get_Call {
	return &GameRepository_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *GameRepository_Get_Call) Run(run func(id uuid.UUID)) *GameRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID))
	})
	return _c
}

func (_c *GameRepository_Get_Call) Return(_a0 domain.Game, _a1 error) *GameRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_Get_Call) RunAndReturn(run func(uuid.UUID) (domain.Game, error)) *GameRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: game
func (_m *GameRepository) Save(game domain.Game) error {
	ret := _m.Called(game)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.Game) error); ok {
		r0 = rf(game)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GameRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type GameRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - game domain.Game
func (_e *GameRepository_Expecter) Save(game interface{}) *GameRepository_Save_Call {
	return &GameRepository_Save_Call{Call: _e.mock.On("Save", game)}
}

func (_c *GameRepository_Save_Call) Run(run func(game domain.Game)) *GameRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.Game))
	})
	return _c
}

func (_c *GameRepository_Save_Call) Return(_a0 error) *GameRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *GameRepository_Save_Call) RunAndReturn(run func(domain.Game) error) *GameRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// ShowAllAvailableGames provides a mock function with no fields
func (_m *GameRepository) ShowAllAvailableGames() ([]domain.Game, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ShowAllAvailableGames")
	}

	var r0 []domain.Game
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]domain.Game, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []domain.Game); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Game)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GameRepository_ShowAllAvailableGames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ShowAllAvailableGames'
type GameRepository_ShowAllAvailableGames_Call struct {
	*mock.Call
}

// ShowAllAvailableGames is a helper method to define mock.On call
func (_e *GameRepository_Expecter) ShowAllAvailableGames() *GameRepository_ShowAllAvailableGames_Call {
	return &GameRepository_ShowAllAvailableGames_Call{Call: _e.mock.On("ShowAllAvailableGames")}
}

func (_c *GameRepository_ShowAllAvailableGames_Call) Run(run func()) *GameRepository_ShowAllAvailableGames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *GameRepository_ShowAllAvailableGames_Call) Return(_a0 []domain.Game, _a1 error) *GameRepository_ShowAllAvailableGames_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *GameRepository_ShowAllAvailableGames_Call) RunAndReturn(run func() ([]domain.Game, error)) *GameRepository_ShowAllAvailableGames_Call {
	_c.Call.Return(run)
	return _c
}

// NewGameRepository creates a new instance of GameRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameRepository {
	mock := &GameRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
